Bumping into this error:

relation "artists" does not exist
LINE 1: INSERT INTO artists (first_name, last_name) VALUES ('Roger',...
                    ^

Traceback (most recent call last):
  File "/Users/tonydoyle/_Code/_code_clan/e63_class_exercises/week_04/day_2/03_music_library_lab/music_app/console.py", line 12, in <module>
    artist_repository.save(artist1)
  File "/Users/tonydoyle/_Code/_code_clan/e63_class_exercises/week_04/day_2/03_music_library_lab/music_app/repositories/artist_repository.py", line 10, in save
    id = results[0]['id']
IndexError: list index out of range